/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.menu;

/**
 *
 * @author camyt
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniAbouth = new javax.swing.JMenuItem();
        mniHelp = new javax.swing.JMenuItem();
        mnuDish = new javax.swing.JMenu();
        mniEnter = new javax.swing.JMenuItem();
        mniModifyD = new javax.swing.JMenuItem();
        mniLookD = new javax.swing.JMenuItem();
        mniDeleteD = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        mniEnterO = new javax.swing.JMenuItem();
        mniModifyO = new javax.swing.JMenuItem();
        mniLookO = new javax.swing.JMenuItem();
        mniDeleteO = new javax.swing.JMenuItem();
        mnuEvent = new javax.swing.JMenu();
        mniEnterE = new javax.swing.JMenuItem();
        mniModifyE4 = new javax.swing.JMenuItem();
        mniLookE = new javax.swing.JMenuItem();
        mniDeleteE = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Lo Nuestro");

        mniAbouth.setText("Acerda de");
        jMenu1.add(mniAbouth);

        mniHelp.setText("Ayuda");
        jMenu1.add(mniHelp);

        jMenuBar1.add(jMenu1);

        mnuDish.setText("Platos");

        mniEnter.setText("Ingresar");
        mnuDish.add(mniEnter);

        mniModifyD.setText("Modificar");
        mnuDish.add(mniModifyD);

        mniLookD.setText("Buscar");
        mnuDish.add(mniLookD);

        mniDeleteD.setText("Eliminar");
        mniDeleteD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeleteDActionPerformed(evt);
            }
        });
        mnuDish.add(mniDeleteD);

        jMenuBar1.add(mnuDish);

        mnuOrder.setText("Ordenes");

        mniEnterO.setText("Ingresar");
        mnuOrder.add(mniEnterO);

        mniModifyO.setText("Modificar");
        mniModifyO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModifyOActionPerformed(evt);
            }
        });
        mnuOrder.add(mniModifyO);

        mniLookO.setText("Buscar");
        mnuOrder.add(mniLookO);

        mniDeleteO.setText("Eliminar");
        mnuOrder.add(mniDeleteO);

        jMenuBar1.add(mnuOrder);

        mnuEvent.setText("Eventos");

        mniEnterE.setText("Ingresar");
        mnuEvent.add(mniEnterE);

        mniModifyE4.setText("Modificar");
        mnuEvent.add(mniModifyE4);

        mniLookE.setText("Buscar");
        mniLookE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLookEActionPerformed(evt);
            }
        });
        mnuEvent.add(mniLookE);

        mniDeleteE.setText("Eliminar");
        mnuEvent.add(mniDeleteE);

        jMenuBar1.add(mnuEvent);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDeleteDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeleteDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDeleteDActionPerformed

    private void mniModifyOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModifyOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniModifyOActionPerformed

    private void mniLookEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLookEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniLookEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniAbouth;
    private javax.swing.JMenuItem mniDeleteD;
    private javax.swing.JMenuItem mniDeleteE;
    private javax.swing.JMenuItem mniDeleteO;
    private javax.swing.JMenuItem mniEnter;
    private javax.swing.JMenuItem mniEnterE;
    private javax.swing.JMenuItem mniEnterO;
    private javax.swing.JMenuItem mniHelp;
    private javax.swing.JMenuItem mniLookD;
    private javax.swing.JMenuItem mniLookE;
    private javax.swing.JMenuItem mniLookO;
    private javax.swing.JMenuItem mniModifyD;
    private javax.swing.JMenuItem mniModifyE4;
    private javax.swing.JMenuItem mniModifyO;
    private javax.swing.JMenu mnuDish;
    private javax.swing.JMenu mnuEvent;
    private javax.swing.JMenu mnuOrder;
    // End of variables declaration//GEN-END:variables
}
