/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.restaurantSystem.view;

import ec.edu.espe.restaurantSystem.model.Account;
import javax.swing.ImageIcon;

/**
 *
 * @author camyt
 */
public class FrmMenuEmployee extends javax.swing.JFrame {
    private static Account user;
    /**
     * Creates new form FrmMenuEmployee
     */
    public FrmMenuEmployee(Account user) {
        initComponents();
        this.user = user;
        this.setTitle("\tLo Nuestro Restaurant  | "+user.getName()+" - Empleado");
        setIconImage(new ImageIcon(getClass().getResource("/ec/edu/espe/restaurantSystem/view/img/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEmployee = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnuMenu = new javax.swing.JMenu();
        mnuEvent = new javax.swing.JMenu();
        mnuItmSchedule = new javax.swing.JMenuItem();
        mnuItmNewEvent = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        mnuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jMenuEmployee.setText("Lo Nuestro R&E");
        jMenuEmployee.setToolTipText("Boton Lo Nuestro");

        jMenu3.setText("Acerca de");
        jMenuEmployee.add(jMenu3);

        jMenu4.setText("Ayuda");
        jMenuEmployee.add(jMenu4);

        jMenuBar1.add(jMenuEmployee);

        mnuMenu.setText("Menu");
        mnuMenu.setToolTipText("Boton Menu");
        jMenuBar1.add(mnuMenu);

        mnuEvent.setText("Eventos");
        mnuEvent.setToolTipText("Boton de eventos");

        mnuItmSchedule.setText("Agenda");
        mnuItmSchedule.setToolTipText("Agendar evento");
        mnuItmSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuItmScheduleMouseClicked(evt);
            }
        });
        mnuItmSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmScheduleActionPerformed(evt);
            }
        });
        mnuEvent.add(mnuItmSchedule);

        mnuItmNewEvent.setText("Nuevo Evento");
        mnuItmNewEvent.setToolTipText("Ingresar nuevo evento");
        mnuItmNewEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuItmNewEventMouseClicked(evt);
            }
        });
        mnuItmNewEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmNewEventActionPerformed(evt);
            }
        });
        mnuEvent.add(mnuItmNewEvent);

        jMenuBar1.add(mnuEvent);

        mnuOrder.setText("Ordenes");
        mnuOrder.setToolTipText("Boton de ordenes");
        jMenuBar1.add(mnuOrder);

        mnuHelp.setText("Ayuda");
        mnuHelp.setToolTipText("Ayuda");
        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItmScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItmScheduleMouseClicked
        // TODO add your handling code here:
        FrmScheduleEvent schedule = new FrmScheduleEvent();
        schedule.setUser(user);
        schedule.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItmScheduleMouseClicked

    private void mnuItmScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmScheduleActionPerformed
        // TODO add your handling code here:
        FrmScheduleEvent schedule = new FrmScheduleEvent();
        schedule.setUser(user);
        schedule.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItmScheduleActionPerformed

    private void mnuItmNewEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItmNewEventMouseClicked
        // TODO add your handling code here:
        FrmEvent frmE = new FrmEvent();
        frmE.setUser(user);
        frmE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItmNewEventMouseClicked

    private void mnuItmNewEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmNewEventActionPerformed
        // TODO add your handling code here:
        FrmEvent frmE = new FrmEvent();
        frmE.setUser(user);
        frmE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItmNewEventActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuEmployee(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEmployee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuEvent;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuItmNewEvent;
    private javax.swing.JMenuItem mnuItmSchedule;
    private javax.swing.JMenu mnuMenu;
    private javax.swing.JMenu mnuOrder;
    // End of variables declaration//GEN-END:variables
    /**
     * @return the user
     */
    public Account getUser() {
        return user;
    }

    /**
     * @param user the user to set
     */
    public void setUser(Account user) {
        this.user = user;
    }
    
}
