/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.restaurantSystem.view;

import ec.edu.espe.restaurantSystem.model.Account;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FrmMenuManager extends javax.swing.JFrame {
    private static Account user;
    

    /**
     * Creates new form frmMenu
     * @param user
     */
    public FrmMenuManager(Account user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
        this.setTitle("\tLo Nuestro Restaurant  | "+user.getName()+" - Administrador");
        setIconImage(new ImageIcon(getClass().getResource("/ec/edu/espe/restaurantSystem/view/img/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMenuAdmin = new javax.swing.JMenu();
        mnuItmAbout = new javax.swing.JMenuItem();
        mnuItmExit = new javax.swing.JMenuItem();
        mnuMenu = new javax.swing.JMenu();
        mnuEvent = new javax.swing.JMenu();
        mnuItmSchedule = new javax.swing.JMenuItem();
        mnuItmNewEvent = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        mnuManagement = new javax.swing.JMenu();
        mnuItmDish = new javax.swing.JMenuItem();
        mnuItmServices = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenu();
        mnuItmOrder = new javax.swing.JMenuItem();
        mnuItmEvent = new javax.swing.JMenuItem();
        mnuAccount = new javax.swing.JMenu();
        mnuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Menu"); // NOI18N
        setSize(new java.awt.Dimension(800, 600));

        mnuMenuAdmin.setText("Lo Nuestro R&E");
        mnuMenuAdmin.setToolTipText("Boton lo nuestro");

        mnuItmAbout.setText("Acerca de..");
        mnuMenuAdmin.add(mnuItmAbout);

        mnuItmExit.setText("Salir");
        mnuItmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmExitActionPerformed(evt);
            }
        });
        mnuMenuAdmin.add(mnuItmExit);

        jMenuBar1.add(mnuMenuAdmin);

        mnuMenu.setText("Menu");
        mnuMenu.setToolTipText("Mostrar el menu del restaurante");
        mnuMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuMenu);

        mnuEvent.setText("Eventos");
        mnuEvent.setToolTipText("Ingresar eventos");

        mnuItmSchedule.setText("Agenda");
        mnuItmSchedule.setToolTipText("Agendar eventos");
        mnuItmSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuItmScheduleMouseClicked(evt);
            }
        });
        mnuItmSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmScheduleActionPerformed(evt);
            }
        });
        mnuEvent.add(mnuItmSchedule);

        mnuItmNewEvent.setText("Nuevo Evento");
        mnuItmNewEvent.setToolTipText("Ingresar nuevo evento");
        mnuItmNewEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuItmNewEventMouseClicked(evt);
            }
        });
        mnuItmNewEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmNewEventActionPerformed(evt);
            }
        });
        mnuEvent.add(mnuItmNewEvent);

        jMenuBar1.add(mnuEvent);

        mnuOrder.setText("Ordenes");
        mnuOrder.setToolTipText("Ingresar ordenes");
        mnuOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOrderMouseClicked(evt);
            }
        });
        mnuOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOrderActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuOrder);

        mnuManagement.setText("Gestión");
        mnuManagement.setToolTipText("Ingresar nuevos platos o eventos");

        mnuItmDish.setText("Nuevo Plato");
        mnuItmDish.setToolTipText("Ingresar nuevo plato");
        mnuItmDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmDishActionPerformed(evt);
            }
        });
        mnuManagement.add(mnuItmDish);

        mnuItmServices.setText("Servicios para Eventos");
        mnuItmServices.setToolTipText("Mostrar servicios");
        mnuManagement.add(mnuItmServices);

        jMenuBar1.add(mnuManagement);

        mnuReport.setText("Reportes");
        mnuReport.setToolTipText("Reportes de ventas");

        mnuItmOrder.setText("Ordenes");
        mnuItmOrder.setToolTipText("Mostrar ordenes");
        mnuItmOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmOrderActionPerformed(evt);
            }
        });
        mnuReport.add(mnuItmOrder);

        mnuItmEvent.setText("Eventos");
        mnuItmEvent.setToolTipText("Mostrar eventos");
        mnuReport.add(mnuItmEvent);

        jMenuBar1.add(mnuReport);

        mnuAccount.setText("Cuentas");
        mnuAccount.setToolTipText("Ingresar nueva cuenta");
        mnuAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAccountMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuAccount);

        mnuHelp.setText("Ayuda");
        mnuHelp.setToolTipText("Mostrar ayuda");
        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAccountMouseClicked
        // TODO add your handling code here:
        FrmNewAccount account = new FrmNewAccount();
        account.setUser(user);
        account.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuAccountMouseClicked

    private void mnuMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMenuMouseClicked
        // TODO add your handling code here:
        FrmMenuOption menuOp = new FrmMenuOption();
        menuOp.setUser(user);
        menuOp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuMenuMouseClicked

    private void mnuItmNewEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItmNewEventMouseClicked
        // TODO add your handling code here:
        FrmEvent frmE = new FrmEvent();
        frmE.setUser(user);
        frmE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItmNewEventMouseClicked

    private void mnuItmScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItmScheduleMouseClicked
        // TODO add your handling code here:
        FrmScheduleEvent schedule = new FrmScheduleEvent();
        schedule.setUser(user);
        schedule.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItmScheduleMouseClicked

    private void mnuOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOrderMouseClicked
        // TODO add your handling code here:
       FrmOrder order= new FrmOrder();
       order.setUser(user);
        order.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuOrderMouseClicked

    private void mnuItmDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmDishActionPerformed
        // TODO add your handling code here:
        FrmDish dish = new FrmDish();
        dish.setUser(user);
        dish.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItmDishActionPerformed

    private void mnuItmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmExitActionPerformed
        // TODO add your handling code here:
        int index = JOptionPane.showConfirmDialog(this, "Salir del Programa?");
        if (index == 0) {
            FrmLogin login = new FrmLogin();
            login.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_mnuItmExitActionPerformed

    private void mnuItmScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmScheduleActionPerformed
        // TODO add your handling code here:
        FrmScheduleEvent schedule = new FrmScheduleEvent();
        schedule.setUser(user);
        schedule.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItmScheduleActionPerformed

    private void mnuItmNewEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmNewEventActionPerformed
        // TODO add your handling code here:
        FrmEvent frmE = new FrmEvent();
        frmE.setUser(user);
        frmE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItmNewEventActionPerformed

    private void mnuOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOrderActionPerformed
        // TODO add your handling code here:
        FrmOrder order= new FrmOrder();
        order.setUser(user);
        order.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuOrderActionPerformed

    private void mnuItmOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmOrderActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
    }//GEN-LAST:event_mnuItmOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuManager(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuAccount;
    private javax.swing.JMenu mnuEvent;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuItmAbout;
    private javax.swing.JMenuItem mnuItmDish;
    private javax.swing.JMenuItem mnuItmEvent;
    private javax.swing.JMenuItem mnuItmExit;
    private javax.swing.JMenuItem mnuItmNewEvent;
    private javax.swing.JMenuItem mnuItmOrder;
    private javax.swing.JMenuItem mnuItmSchedule;
    private javax.swing.JMenuItem mnuItmServices;
    private javax.swing.JMenu mnuManagement;
    private javax.swing.JMenu mnuMenu;
    private javax.swing.JMenu mnuMenuAdmin;
    private javax.swing.JMenu mnuOrder;
    private javax.swing.JMenu mnuReport;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the user
     */
    public Account getUser() {
        return user;
    }

    /**
     * @param user the user to set
     */
    public void setUser(Account user) {
        this.user = user;
    }
}
